force-app/main/default/objects/Account/fields/NPI__c.field-meta.xml
<CustomField>
    <fullName>NPI__c</fullName>
    <description>National Provider Identification</description>
    <label>NPI</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/HealthcareProvider/fields/NPI__c.field-meta.xml
<CustomField>
    <fullName>NPI__c</fullName>
    <label>NPI</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MemberPlan/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>Policy Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MemberPlan/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria. [Business]</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Member Plans</relationshipLabel>
    <relationshipName>Member_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MemberPlan/fields/Service_Detail__c.field-meta.xml
<CustomField>
    <fullName>Service_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Detail</label>
    <referenceTo>Service_Detail__c</referenceTo>
    <relationshipLabel>Member Plans</relationshipLabel>
    <relationshipName>Member_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Detail__c/Service_Detail__c.object-meta.xml
<CustomObject>
    <label>Service Detail</label>
    <nameField>
        <label>Service Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Detail__c/fields/Diagnosis_Code__c.field-meta.xml
<CustomField>
    <fullName>Diagnosis_Code__c</fullName>
    <label>Diagnosis Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Detail__c/fields/Procedure_Code__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Code__c</fullName>
    <label>Procedure Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Detail__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultation</fullName>
            </value>
            <value>
                <fullName>Infusion</fullName>
            </value>
            <value>
                <fullName>Surgery</fullName>
            </value>
            <value>
                <fullName>Check-up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HealthCloudBenefitVerifyHandlerTest.cls
@isTest
public with sharing class HealthCloudBenefitVerifyHandlerTest {
    //static Id memberPlanId;
    //static Id providerId;
    static Id payerId;
    static Id memberId;
    static Id personAccountRTId;
    
    @IsTest
    static void testVerifyBenefits() {
        /**
         * Had issuses with account records in test setup method so I moved
         * test data creation into each test method
         */
        
        // Create Account records
        Account provider = new Account(
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId(),
            Name = 'Test Provider',
            NPI__c = 1234567890
        );
        insert provider;

        personAccountRTId = [
        SELECT Id 
        FROM RecordType 
        WHERE SObjectType = 'Account' AND IsPersonType = true 
        LIMIT 1
        ].Id;

        // Create Member records
        Account member = new Account(
            RecordTypeId = personAccountRTId,  
            FirstName = 'Test',
            LastName = 'Member',
            PersonBirthdate = Date.today(),
            PersonGender = 'Male'
        );
        insert member;
        system.debug('Member Id: ' + member.Id);
        memberId = Member.Id;
        system.debug('Member Id Static Var: ' + memberId);
        system.debug('Member Record type id: ' + personAccountRTId);
        

        // Create Payer records
        Account payer = new Account(
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId(),  
            Name = 'Test Payer',
            Type = 'Payer',
            NPI__c = 1236567890
        );

        insert payer;

        // Create Service_Detail__c records
        Service_Detail__c serviceDetail = new Service_Detail__c(
        Service_Type__c = 'Consultation',
        Service_Date__c = Date.today(),
        Procedure_Code__c = '123',
        Diagnosis_Code__c = '1235'
        );
        insert serviceDetail;

        // Create MemberPlan records
        MemberPlan memPlan = new MemberPlan(
            Name = 'Test Member Plan',
            MemberId = member.Id,
            PayerId = payer.Id,
            Policy_Number__c = '1234567890',
            Provider__c = provider.Id,
            GroupNumber = '12345',
            SubscriberId = member.Id
        );
        insert memPlan;

        // Link Service_Detail__c to MemberPlan
        memPlan.Service_Detail__c = serviceDetail.Id;
        update memPlan;

        // Set up the mock callout
        Test.setMock(HttpCalloutMock.class, new MockBenefitVerificationCallout());

        Test.startTest();
        
        // Create a BenefitsVerificationRequest using test data
        healthcloudext.BenefitsVerificationRequest bvr = new healthcloudext.BenefitsVerificationRequest();
        //bvr.benefitsRequestId = cbvr.Id;
        bvr.encounterDate = String.valueOf(Date.today());
        bvr.groupNumber = 'G123';
        bvr.memberAccountId = string.valueOf(memberId);
        bvr.memberNumber = 'M123';
        bvr.payerId = payerId;
        bvr.providerNpi = '1234567890';
        bvr.providerOrganizationName = 'Test Provider Org';
        bvr.providerType = 'Individual';
        bvr.serviceTypeCodes = new List<String>{ '30' };

        // Call the method to test
        List<healthcloudext.BenefitsVerificationResponse> responses = HealthCloudBenefitVerificationHandler.verifyBenefits(new List<healthcloudext.BenefitsVerificationRequest>{bvr});

        Test.stopTest();

        // Assert the response
        System.debug('Responses: ' + String.valueOf(responses));
        Assert.areEqual(1, responses.size(), 'There is one resonse object returned.');
        Assert.areEqual(null, responses[0].errorResponse, 'No error resonse should be returned.');
    }

    @IsTest
    static void testVerifyBenefits_Error() {
         // Create Account records
        Account provider = new Account(
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId(),
            Name = 'Test Provider',
            NPI__c = 1234567890
        );
        insert provider;
        //providerId = provider.Id;

        // Create HealthCareProvider records
        HealthCareProvider healthCareProvider = new HealthCareProvider(
        Name = 'Test HealthCareProvider',
        NPI__c = 0987654321
        );
        insert healthCareProvider;

        personAccountRTId = [
        SELECT Id 
        FROM RecordType 
        WHERE SObjectType = 'Account' AND IsPersonType = true 
        LIMIT 1
        ].Id;

        // Create Member records
        Account member = new Account(
            RecordTypeId = personAccountRTId,  
            FirstName = 'Test',
            LastName = 'Member',
            PersonBirthdate = Date.today(),
            PersonGender = 'Male'
        );
        insert member;
        system.debug('Member Id: ' + member.Id);
        memberId = Member.Id;
        system.debug('Member Id Static Var: ' + memberId);
        system.debug('Member Record type id: ' + personAccountRTId);
        

        // Create Payer records
        Account payer = new Account(
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId(),  
            Name = 'Test Payer',
            Type = 'Payer',
            NPI__c = 1236567890
        );

        insert payer;
        payerId = payer.Id;

        // Create Service_Detail__c records
        Service_Detail__c serviceDetail = new Service_Detail__c(
        Service_Type__c = 'Consultation',
        Service_Date__c = Date.today(),
        Procedure_Code__c = '123',
        Diagnosis_Code__c = '1235'
        );
        insert serviceDetail;

        // Create MemberPlan records
        MemberPlan memPlan = new MemberPlan(
            Name = 'Test Member Plan',
            MemberId = member.Id,
            PayerId = payer.Id,
            Policy_Number__c = '1234567890',
            Provider__c = provider.Id,
            GroupNumber = '12345',
            SubscriberId = member.Id
        );
        insert memPlan;

        // Link Service_Detail__c to MemberPlan
        memPlan.Service_Detail__c = serviceDetail.Id;
        update memPlan;

        // Create a BenefitsVerificationRequest using test data
        healthcloudext.BenefitsVerificationRequest bvr = new healthcloudext.BenefitsVerificationRequest();
        //bvr.benefitsRequestId = 'someRequestId';
        bvr.encounterDate = String.valueOf(Date.today());
        bvr.groupNumber = 'G123';
        bvr.memberAccountId = memberId.toString();
        bvr.memberNumber = 'M123';
        bvr.payerId = payerId.toString();
        bvr.providerNpi = '1234567890';
        bvr.providerOrganizationName = 'Test Provider Org';
        bvr.providerType = 'Individual';
        bvr.serviceTypeCodes = new List<String>{ '30' };

        // Set up the mock callout
        Test.setMock(HttpCalloutMock.class, new MockBenefitVerificationCallout_Error());

        Test.startTest();

        // Call the method to test
        List<healthcloudext.BenefitsVerificationResponse> responses = HealthCloudBenefitVerificationHandler.verifyBenefits(new List<healthcloudext.BenefitsVerificationRequest>{bvr});

        Test.stopTest();

        // Assert the response
        System.assertEquals(1, responses.size());
        System.assertEquals('HTTP 500: Internal Server Error', responses[0].errorResponse);
        //System.assertEquals('Callout failure: Internal Server Error', responses[0].statusReason);
    }

    @IsTest
    static void testVerifyBenefits_ValidationException() {
        // ... (create test data)
        // Create Account records
        //Removed NPI Number to fail validation
        Account provider = new Account(
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId(),
            Name = 'Test Provider'
        );
        insert provider;

        personAccountRTId = [
        SELECT Id 
        FROM RecordType 
        WHERE SObjectType = 'Account' AND IsPersonType = true 
        LIMIT 1
        ].Id;

        // Create Member records
        Account member = new Account(
            RecordTypeId = personAccountRTId,  
            FirstName = 'Test',
            LastName = 'Member',
            PersonBirthdate = Date.today(),
            PersonGender = 'Male'
        );
        insert member;
        system.debug('Member Id: ' + member.Id);
        memberId = Member.Id;
        system.debug('Member Id Static Var: ' + memberId);
        system.debug('Member Record type id: ' + personAccountRTId);
        

        // Create Payer records
        Account payer = new Account(
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId(),  
            Name = 'Test Payer',
            Type = 'Payer',
            NPI__c = 1236567890
        );

        insert payer;
        payerId = payer.Id;

        // Create Service_Detail__c records
        Service_Detail__c serviceDetail = new Service_Detail__c(
        Service_Type__c = 'Consultation',
        Service_Date__c = Date.today(),
        Procedure_Code__c = '123',
        Diagnosis_Code__c = '1235'
        );
        insert serviceDetail;

        // Create MemberPlan records
        MemberPlan memPlan = new MemberPlan(
            Name = 'Test Member Plan',
            MemberId = member.Id,
            PayerId = payer.Id,
            Policy_Number__c = '1234567890',
            Provider__c = provider.Id,
            GroupNumber = '12345',
            SubscriberId = member.Id
        );
        insert memPlan;

        // Link Service_Detail__c to MemberPlan
        memPlan.Service_Detail__c = serviceDetail.Id;
        update memPlan;

        // Create a BenefitsVerificationRequest using test data
        healthcloudext.BenefitsVerificationRequest bvr = new healthcloudext.BenefitsVerificationRequest();
        //bvr.benefitsRequestId = 'someRequestId';
        bvr.encounterDate = String.valueOf(Date.today());
        bvr.groupNumber = 'G123';
        bvr.memberAccountId = memberId.toString();
        bvr.memberNumber = 'M123';
        bvr.payerId = payerId.toString();
        bvr.providerNpi = '1234567890';
        bvr.providerOrganizationName = 'Test Provider Org';
        bvr.providerType = 'Individual';
        bvr.serviceTypeCodes = new List<String>{ '30' };

        // Set up the mock callout
        Test.setMock(HttpCalloutMock.class, new MockBenefitVerificationCallout_400());

        Test.startTest();
        

        // Call the method to test
        List<healthcloudext.BenefitsVerificationResponse> responses = HealthCloudBenefitVerificationHandler.verifyBenefits(new List<healthcloudext.BenefitsVerificationRequest>{bvr});

        Test.stopTest();

        // Assert the response
        Assert.areEqual(1, responses.size(), 'There is one response object returned.');
        Assert.areNotEqual(null, responses[0].errorResponse, 'Error response should be returned.');
    }

 
    public class MockBenefitVerificationCallout implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(200);
            res.setBody(JSON.serialize(new Map<String, Object>{
                'status' => 'Acknowledged',
                'statusReason' => 'Verified successfully'
            }));
            return res;
        }
    }


    public class MockBenefitVerificationCallout_Error implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(500);
            res.setBody('Internal Server Error');
            return res;
        }
    }


    public class MockBenefitVerificationCallout_400 implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(400);
            res.setBody('Bad Request: Missing or invalid payload');
            return res;
        }
}
}